[package]
name = "pdf_reader"
version = "0.1.0"
authors = ["James DeVore <jdevore4592@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf-extract = "0.6.1"
lopdf = "0.23.0"
walkdir = "2"
regex = "1"